### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by vkurup**
Addresses #6.

This updates the work of @yuvallanger in #7 to get the remaining tests to pass. I'm not sure if this repo is still maintained, but wanted to share this if others need a Python 3 version of the library.

Thanks!

```
$ tox
GLOB sdist-make: /home/vkurup/dev/pyfribidi/setup.py
py24 create: /home/vkurup/dev/pyfribidi/.tox/py24
py24 inst: /home/vkurup/dev/pyfribidi/.tox/.tmp/package/1/pyfribidi-0.11.0.zip
py24 installed: pyfribidi==0.11.0,six==1.12.0
py24 run-test-pre: PYTHONHASHSEED='1994857263'
py24 runtests: commands[0] | python test_pyfribidi.py
...........................
----------------------------------------------------------------------
Ran 27 tests in 0.056s

OK
py25 create: /home/vkurup/dev/pyfribidi/.tox/py25
py25 inst: /home/vkurup/dev/pyfribidi/.tox/.tmp/package/1/pyfribidi-0.11.0.zip
py25 installed: pyfribidi==0.11.0,six==1.12.0
py25 run-test-pre: PYTHONHASHSEED='1994857263'
py25 runtests: commands[0] | python test_pyfribidi.py
...........................
----------------------------------------------------------------------
Ran 27 tests in 0.054s

OK
py26 create: /home/vkurup/dev/pyfribidi/.tox/py26
py26 inst: /home/vkurup/dev/pyfribidi/.tox/.tmp/package/1/pyfribidi-0.11.0.zip
py26 installed: pyfribidi==0.11.0,six==1.12.0
py26 run-test-pre: PYTHONHASHSEED='1994857263'
py26 runtests: commands[0] | python test_pyfribidi.py
...........................
----------------------------------------------------------------------
Ran 27 tests in 0.054s

OK
py27 create: /home/vkurup/dev/pyfribidi/.tox/py27
py27 inst: /home/vkurup/dev/pyfribidi/.tox/.tmp/package/1/pyfribidi-0.11.0.zip
py27 installed: pyfribidi==0.11.0,six==1.12.0
py27 run-test-pre: PYTHONHASHSEED='1994857263'
py27 runtests: commands[0] | python test_pyfribidi.py
...........................
----------------------------------------------------------------------
Ran 27 tests in 0.062s

OK
py37 create: /home/vkurup/dev/pyfribidi/.tox/py37
py37 inst: /home/vkurup/dev/pyfribidi/.tox/.tmp/package/1/pyfribidi-0.11.0.zip
py37 installed: pyfribidi==0.11.0,six==1.12.0
py37 run-test-pre: PYTHONHASHSEED='1994857263'
py37 runtests: commands[0] | python test_pyfribidi.py
...........................
----------------------------------------------------------------------
Ran 27 tests in 0.064s

OK
_____________________________________________________________________________________________________ summary _____________________________________________________________________________________________________
  py24: commands succeeded
  py25: commands succeeded
  py26: commands succeeded
  py27: commands succeeded
  py37: commands succeeded
  congratulations :)
```

### CODE REVIEW

**Comment by tobiasmcnulty** [comment]
(Full disclosure: I work with @vkurup)

Is there anything we do to help with finalizing Python 3 support? We have an application we're attempting to upgrade to Python 3, and pyfribidi is our only remaining non-versioned requirement.

For example, we are happy to help with merging and updating PyPI, if needed.

Thanks so much for this project and for your support!

**Comment by v0lk3r** [comment]
I just merged the PR. Maybe a short background why this took so long:
This repository was originally a fork from the official repository since we probably needed a small bugfix or feature for mwlib. I wasn't aware that the pypi page now points to "our" repository as the source of the pyfribidi package...

**Comment by v0lk3r** [comment]
I also just release and uploaded version 0.12.0

**Comment by vkurup** [comment]
Thank you!

**Pull request merged**
